version: '3.3'

services:
  app:
    image: kalisio/kano:dev
    environment:
      - APP_SECRET=xxx
      - LAYERS_FILTER=OSM_BRIGHT OSM_DARK IMAGERY CESIUM_ELLIPSOID K2 U5_S21
      - BUILD_NUMBER
      - NODE_APP_INSTANCE
      - DB_URL
      - DATA_DB_URL
      - CESIUM_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzNmU5ZDA5Yi0yMjc1LTRmYmUtYWJlMy0xZGUyMWNhNDFlNTQiLCJpZCI6NjcyNCwiaWF0IjoxNjA1NjM5NTkwfQ.CJwGZXNmowTDo9nJ6tnmeIcwtXWZN8Q9bzfDyEH3iN8
    volumes:
      - type: bind
        source: ./covid19-layers.js
        target: /opt/kalisio/kano/api/config/layers/covid19-layers.js
    ports:
      - "3000:8081"
    networks:
      - app

networks:
  app:

