version: '3.3'

services:
  app:
    image: kalisio/kano:dev
    environment:
      - APP_SECRET=xxx
      - BUILD_NUMBER
      - NODE_APP_INSTANCE
      - DB_URL
      - DATA_DB_URL
      - CESIUM_TOKEN
    ports:
      - "8081:8081"
    networks:
      - app

networks:
  app:

